version: "3.9"

services:
  grpc-web:
    hostname: grpc-web
    build:
      context: .
      dockerfile: lib/web/Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION:-1.21.3}
        NGINX_PORT: ${NGINX_PORT:-80}
        NGINX_HOST: ${NGINX_HOST:-0.0.0.0}
    tty: true
    stop_signal: SIGTERM
    restart: unless-stopped
    volumes:
      - type: volume
        source: grpc-web-data
        target: /usr/share/nginx/html
        read_only: false
      - type: volume
        source: grpc-web-log
        target: /var/log/nginx
        read_only: true
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "nz", "-zv", "127.0.0.1", "80"]
      interval: 5s
      timeout: 5s
      retries: 60
    privileged: true
    pid: "host"
    stop_grace_period: 5s
    env_file:
      - nginx.env
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    cpu_shares: 4
    networks:
      - grpc-tier
