version: "3.9"

services:
  grpc-web:
    image: nginx/grpc-web/dev
    container_name: nginx-grpc-web-dev
    extends:
      file: base/docker-compose.base.yml
      service: grpc-web
    ports:
      - protocol: TCP
        published: ${NGINX_PORT:-80}
        target: ${NGINX_PORT:-80}
      - protocol: TCP
        published: ${NGINX_SSL_PORT:-443}
        target: ${NGINX_SSL_PORT:-443}
    volumes:
      - type: bind
        source: base/nginx/config/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: base/nginx/config/template
        target: /etc/nginx/template
        read_only: true
      - type: bind
        source: base/nginx/config/default.http.conf
        target: /etc/nginx/conf.d/default.http.conf
        read_only: true
      - type: bind
        source: base/nginx/config/default.stream.conf
        target: /etc/nginx/conf.d/default.stream.conf
        read_only: true
    expose:
      - ${NGINX_PORT:-80}
      - ${NGINX_SSL_PORT:-443}
  # grpc-server:
  #   extends:
  #     file: ../dev/server/docker-compose.yml
  #     service: grpc-web
