# MIT License

# Copyright (c) 2021 Emil Shari <emil.shari87@gmail.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "3.9"

services:
  grpc-server:
    image: node/grpc-server/prod
    container_name: node-grpc-server-prod
    extends:
      file: prod/docker-compose.prod.yml
      service: grpc-server
    ports:
      - protocol: TCP
        published: ${NODE_PORT:-8080}
        target: ${NODE_PORT:-8080}
    expose:
      - ${NODE_PORT:-8080}
  grpc-web:
    image: nginx/grpc-web/prod
    container_name: nginx-grpc-web-prod
    extends:
      file: base/docker-compose.base.yml
      service: grpc-web
    ports:
      - protocol: TCP
        published: ${NGINX_PORT:-80}
        target: ${NGINX_PORT:-80}
      - protocol: TCP
        published: ${NGINX_SSL_PORT:-443}
        target: ${NGINX_SSL_PORT:-443}
    expose:
      - ${NGINX_PORT:-80}
      - ${NGINX_SSL_PORT:-443}
