version: "3.9"

services:
  grpc-web:
    image: nginx/grpc-web/ci
    container_name: nginx-grpc-web-ci
    extends:
      file: ../base/docker-compose.base.yml
      service: grpc-web
  grpc-server:
    image: node/grpc-server/ci
    container_name: node-grpc-server-ci
    extends:
      file: ../prod/docker-compose.prod.yml
      service: grpc-server
