apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-volume
  namespace: nginx
  labels:
    app: nginx-persistent
    tier: nginx
    role: persistent
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-log-pvc-volume
  namespace: nginx
  labels:
    app: nginx-persistent
    tier: nginx
    role: persistent
spec:
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: postgresql-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
