apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
  labels:
    app: nginx-persistent
    tier: nginx
    role: persistent
data:
  NGINX_VERSION: '1.21.3'
  NGINX_PORT: '80'
  NGINX_SSL_PORT: '443'
  NGINX_HOST: '0.0.0.0'
