apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-log-pv-volume
  namespace: nginx
  labels:
    type: local
spec:
  capacity:
    storage: 12Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual

  hostPath:
    path: /mnt/sda1/var/log/nginx/
    type: DirectoryOrCreate
